#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
 ~/.config/polybar/launch.sh --forest
wmname LG3D &
# if [ -z "$(pgrep picom)" ] ; then
    # picom --experimental-backends -b &
# fi

export _JAVA_AWT_WM_NONREPARENTING=1

# Redshift
# if [ -z "$(pgrep redshift)" ] ; then
    # redshift &
# fi
#
# if [ -z "$(pgrep synapse)" ] ; then
    # synapse -c &
# fi
#
#~/.config/polybar/launch.sh --cuts

#tray
setxkbmap -option caps:swapescape

# Power manager
# if [ -z "$(pgrep mate-power-manager)" ] ; then
    # mate-power-manager &
# fi
#
#start notifiation daemon
# if [ -z "$(pgrep dunst)" ] ; then
    # dunst -config /home/brown/.config/dunst/dunstrc &
# fi
#
# if [ -z "$(pgrep mate-volume-control-status-icon)" ] ; then
    # mate-volume-control-status-icon &
# fi
#
# Screensaver
# if [ -z "$(pgrep xscreensaver)" ] ; then
    # xscreensaver -no-splash &
# fi
#
# Wallpaper
# if [ -z "$(pgrep nitrogen)" ] ; then
    # nitrogen --set-zoom-fill --random /home/brown/.local/share/wallpapers/ &
# fi
#
# Bluetooth
# if [ -z "$(pgrep blueman-applet)" ] ; then
   # blueman-applet &
# fi
#
# Network Applet
# if [ -z "$(pgrep nm-applet)" ] ; then
    # nm-applet &
# fi
#
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3 
bspc config window_gap           10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false 
bspc config active_border_color  "#88ff00"
bspc config normal_border_color  "#1E1E1E"
bspc config focused_border_color "#3F88C5"
# bspc config focused_border_color "#FF6347"
bspc config bottom_padding       -9 
bspc config left_padding         0 
bspc config right_padding        0
bspc config top_padding          30 
bspc config ignore_ewmh_focus    false
bspc config click_to_focus      true 
bspc config focus_by_distance    true
bspc config focus_follows_pointer false
bspc config history_aware_focus  true
bspc config pointer_modifier     mod1 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner 

bspc rule -a Gimp-2.10 desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Mate-terminal desktop='^2' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^8' follow=on
bspc rule -a Zeal desktop='^10' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a Caja desktop='^3' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a FireFox desktop='^1' follow=on
bspc rule -a Nightly desktop='^1' follow=on
bspc rule -a Navigator desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^7' follow=on
bspc rule -a Wpsoffice desktop='^0' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a libreoffice-writer desktop='^0' follow=on
bspc rule -a libreoffice-startcenter desktop='^0' follow=on
bspc rule -a libreoffice-base desktop='^0' follow=on
bspc rule -a okular desktop='^6' follow=on
bspc rule -a jetbrains-idea desktop='^4'
bspc rule -a jetbrains-pycharm desktop='^4'
bspc rule -a "Foxit Reader" desktop='^6' follow=on
bspc rule -a "Atril" desktop='^6' follow=on
bspc rule -a Evince desktop='^6' follow=on
bspc rule -a Eclipse desktop='^4' follow=on
bspc rule -a jetbrains-idea-ce desktop='^4'
bspc rule -a discord desktop='^9'
bspc rule -a VSCodium desktop='^4'

xrdb -merge .Xresources
exec dbus-launch bspwm
