#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="vim"
# DMENUEDITOR="nvim"
DMEDITOR="alacritty -e nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
"SpaceVim - $HOME/.SpaceVim.d/init.toml"
"Leetcode - $HOME/Documents/Geeny/C++/leetcode/leetcode.cpp"
"Project - $HOME/Documents/My_Doc/Project/Project_Chapter1.tex"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"Vim - $HOME/.SpaceVim/vimrc"
"Nvim - $HOME/.config/nvim/init.vim"
"NvimLua - $HOME/.config/nvim/lua/config.lua"
"Tmux - $HOME/.tmux.conf"
"picom - $HOME/.config/picom/picom.conf"
"polybar - $HOME/.config/polybar/cuts"
"Alacritty - $HOME/.config/alacritty.yml"
"Kitty - $HOME/.config/kitty/kitty.conf"
"sxhkd - $HOME/.config/sxhkd/sxhkdrc"
"Xresources - $HOME/.Xresources"
"Xsessions - $HOME/.xsession"
"zsh - $HOME/.zshrc"
"Rofi - $HOME/.config/rofi/config.rasi"
"RofiScript - $HOME/.config/rofi/scripts/config"
"Search - $HOME/.config/rofi/scripts/search"
"Bookmark - $HOME/.config/rofi/scripts/site"
"fish - $HOME/.config/fish/config.fish"
"bash - $HOME/.bashrc"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i  20 -p 'Edit config:')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi
